name: rsim
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - requests>=2.25.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pytest>=6.0.0
  - black>=21.0.0
  - flake8>=3.9.0
  - pip
  - pip:
    - ta-lib>=0.4.24
    - TA-Lib>=0.4.24
    - pandas-ta>=0.3.14b0
    - yfinance>=0.1.87
    - alpha-vantage>=2.3.1
    - quandl>=3.7.0